### ISSUE TITLE
Omit scrobbling support from release

### ISSUE THREAD

**Issue by cheshire137** [cheshire137/huxleyfm#14]
Out of respect for SomaFM's wishes, I'll omit Last.fm scrobbling support from the release others will be able to download. Scrobbling will still be possible if you build the app yourself and provide your own Last.fm API keys.

**Comment by skywinder** [comment]
Hi. What the reason to hide last.fm from release version?
Is this feature works?
Just found this line: https://github.com/cheshire137/huxleyfm/blob/c038541b913948888f582bf803b1a5fcdd2f724d/settings/settings.html#L2

Can you specify, there should I put API key in the app?

**Comment by cheshire137** [comment]
> What the reason to hide last.fm from release version?

I thought the discussion took place in this repo, but it was actually in another repository of mine for listening to SomaFM. Check out the thread starting at https://github.com/cheshire137/soma-chrome/issues/39#issuecomment-362104481 for some backstory on not supporting Last.fm scrobbling with SomaFM players. For context, `@rustyhodge` works at SomaFM.

> Is this feature works?

It should work okay, yeah, it just requires some manual work to set a config variable. I think these docs are up to date, but let me know if they don't work for you! https://github.com/cheshire137/huxleyfm/blob/c038541b913948888f582bf803b1a5fcdd2f724d/README.md#how-to-develop

**Comment by skywinder** [comment]
@cheshire137 thanks for the explanation.

BTW, I'm also switching to open alternative of lastfm:  
- Libre.fm 
- https://musicbrainz.org/

Now I'm choosing which is suits better my need. Would you mind to consider to support these services?

**Comment by cheshire137** [comment]
I wouldn't be opposed to support in the app for either or both of those, though I also don't use them so they wouldn't be a priority for me personally to add. I'd also be interested in `@rustyhodge`'s thoughts on adding support for things similar to Last.fm. I don't know if he's opposed to Last.fm in particular or the idea of reproducing Soma's track lists on any non-Soma site.
