### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by ghost** [cheshire137/huxleyfm#27]
Instead of just "HuxleyFM", the window title should add the song and/or artist. Some examples:
- Slow This Bird Down - HuxleyFM
- Boards of Canada - HuxleyFM
- Slow This Bird Down - Boards of Canada - HuxleyFM
- Boards of Canada - Slow This Bird Down - HuxleyFM

**Comment by cheshire137** [comment]
This might get annoying, trying to Cmd-Tab/Alt-Tab to a window with a really long title that gets cut off.

**Comment by ghost** [comment]
? Most programs do this, like Firefox

**Comment by cheshire137** [comment]
Fair enough. I'm usually on a Mac where I don't see app titles changing, but I just spent some time in Windows 10 and I see what you mean.
